// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvaApi.Db;

#nullable disable

namespace ProvaApi.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230801150415_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("ProvaApi.Db.DDato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("descrizione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("idUtente")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("dato");
                });

            modelBuilder.Entity("ProvaApi.Db.DPersona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("persona");
                });
#pragma warning restore 612, 618
        }
    }
}
